# Generated by Django 4.2.13 on 2024-06-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_product_discounted_price_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_date', models.DateTimeField(verbose_name='زمان پایان')),
                ('discount_percentage', models.IntegerField(verbose_name='درصد تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
    ]
