# Generated by Django 4.2.13 on 2024-06-20 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=300, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مشخصات فنی',
                'verbose_name_plural': 'مشخصات فنی',
            },
        ),
    ]
