# Generated by Django 4.2.13 on 2024-06-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_technicalspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_keys', to='product_module.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کلید مشخصات',
                'verbose_name_plural': 'کلیدهای مشخصات',
            },
        ),
        migrations.AlterField(
            model_name='technicalspecification',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specifications', to='product_module.specificationkey', verbose_name='کلید'),
        ),
    ]
