# Generated by Django 3.2.8 on 2024-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد رهگیری'),
        ),
    ]
