# Generated by Django 4.2.13 on 2024-06-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تعداد محصول'),
        ),
    ]
