# Generated by Django 4.2.13 on 2024-06-19 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_discountcode'),
        ('order_module', '0008_alter_orderdetail_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.discountcode', verbose_name='کد تخفیف'),
        ),
    ]
