# Generated by Django 4.2.8 on 2024-05-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0007_remove_user_about_user_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='ostan',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='shahrestan',
        ),
    ]
