# Generated by Django 4.2.8 on 2024-05-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('account_module', '0008_rename_state_user_ostan_rename_city_user_shahrestan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ostan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iranian_cities.ostan', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shahrestan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iranian_cities.shahrestan', verbose_name='شهر'),
        ),
    ]
